### ISSUE TITLE
Config: Tracker Invalid Value in vrconfig.yml

### ISSUE THREAD

**Issue by unlogisch04** [SlimeVR/SlimeVR-Server#1259]
User reported wrong tracker height. (Tracker below floor)
He did add before the problem occurred new trackers.

To resolve the issue the user had to delete the vrconfig.yml
I did compare then the old and new vonfig and found the following tracker entry:
```
trackers:
  ? ""
  : customName: null
    designation: null
    hide: false
    adjustment: null
    mountingOrientation: null
    mountingResetOrientation: null
    allowDriftCompensation: false
    shouldHaveMagEnabled: null
```

A physical tracker should look like this:
```
  udp://xx:xx:xx:xx:xx:xx/0:
    customName: null
    designation: "body:left_lower_leg"
    hide: false
    adjustment: null
    mountingOrientation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -0.0
    mountingResetOrientation: null
    allowDriftCompensation: true
    shouldHaveMagEnabled: true
```
A virtual ( i think it is at least):
```
  Chest:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingOrientation: null
    mountingResetOrientation: null
    allowDriftCompensation: false
    shouldHaveMagEnabled: null
```

So it seems that there is a tracker name that makes a invalid vrconfig.yml
